name: 🔧 Dev Workflow - Run Tests

on:   
  pull_request:
    branches:
      - master
      
jobs:
  build_test:
    name: 🔧 Test
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: 🟩 Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    - name: 📥 Install Dependencies
      run: npm ci

    - name: 🔧 Run Tests
      run: npm test